LNSSPsd/PhoenixBuilder

- BDump File Format.md
- fastbuilder/configuration/configuration.go
- fastbuilder/i18n/cn.go
- fastbuilder/i18n/en.go
- fastbuilder/i18n/i18n.go
- main.go
BDX:
add official compress quality info
char * encoding info
lastOutput* notify of commandblock
main.go:
add notify when bot is not granted op
add notify when sendcommandfeedback=false
> Minor fix on notify

- README-cn.md
- fastbuilder/configuration/configuration.go
- fastbuilder/i18n/cn.go
- fastbuilder/i18n/en.go
- fastbuilder/i18n/i18n.go
- fastbuilder/parsing/parsing.go
- fastbuilder/task/task.go
- fastbuilder/types/configuration.go
- fyne-gui/gui/profiles/session/tasks/ui.go
- fyne-gui/main.go
在 async 模式下，允许用户以 -resume 参数从某个断点继续构建，适用于一个大任务部分失败的情况
> allow resume

- omega/components/omega_side/controller.go
- omega/components/omega_side/msg.go
经过一段时间的测试和使用，并没有复现所描述的错误，应该是被成功修复了
> Try to fix #102

- .github/workflows/build.yml
Build pre-built packages in Action and release them to Release on version update
> Upload artifacts to Releases after build

- install.sh
> Provide Github Release download source support for all platform

- install.sh
> Fix the error output when setting environment variables

- install.sh
> Fix download link on some Linux platforms

- omega/components/omega_side/deploy.go
> 将url指向正确的目录

- fastbuilder/bdump/command/place_block_with_block_states.go
- fastbuilder/builder/bdump.go
> fix some bugs

- mirror/interface.go
- omega/utils/structure/bdx.go
- omega/utils/structure/builder.go
- omega/utils/structure/define.go
- omega/utils/structure/pos.go
This is my first time to really learn the go language. I may not write it very well. Forgive me.
> The omega universeImport component now supports the latest bdump file format

- omega/components/universeImport/entry.go
- omega/defines/organization.go
- omega/mainframe/game_ctrl.go
- omega/utils/structure/builder.go
- 修复了 `Omega` 的 `统一导入系统` 组件不能向非 `主世界` 维度导入方块的问题
> Fix an issue where imports can not be performed for the Nether and the End dimension

- go.sum
- omega/components/IDS.go
- omega/mainframe/core_components.go
- omega/mainframe/default_components.json
将随机巡逻功能从`手持32k检测`组件中剥离出来，并将其转换为新的核心组件(`CoreComponent`)
同时，为该功能增加以下配置项：
1. 允许设置是否隐藏(隐身)机器人
2. 允许设置是否在玩家上线时进行传送，以确保能够及时获取需要的数据
3. 允许设置将机器人固定到主世界维度，以确保部分功能的运行不会出现问题
> Omega-随机巡逻组件

- io/special_tasks/lexport.go
Please do not delete comments, or you may not understand the meaning later
（实际上主要是方便我后续维护，我需要这些注释）
> Solved the problem of losing blocks forever

- minecraft/protocol/packet/adventure_settings.go
- omega/defines/organization.go
- omega/mainframe/game_ctrl.go
- omega/third_party/liliya/AbilityManage.go
修改：
1. 使 `adventure_settings` 数据包的 `ActionPermission` 与实际情况一致
2. 将 Omega 的 `PlayerKit` 的 `HasPermission` 与 `SetPermission` 修改为以下能力相关的功能
- GetAdventureFlag(key uint32) (bool, error)
- SetAdventureFlag(key uint32, value bool) bool
- GetActionPermission(key uint32) (bool, error)
- SetActionPermission(key uint32, value bool) bool
3. 为 `能力管理` 组件增加注释与优化
> adventure_settings 相关修改

- omega/components/omega_side/side/omega_python_plugins/告示牌&潜影盒_by_Mono.py
> 检测告示牌&潜影盒信息并储存 

- omega/components/omega_side/msg.go
- omega/components/omega_side/side/omega_side/python3_omega_sync/core.py
- omega/components/omega_side/side/omega_side/python3_omega_sync/protocol.py
- omega/components/omega_side/side/只写了一部分的开发文档.md
Omega Side添加发送数据包函数send_packet
> OmegaSide-发送数据包

- omega/components/ban_time.go
- omega/components/cdkey.go
> Omega数据文件升级修改

- fastbuilder/bdump/path/fyne_dedicate.go
- fastbuilder/builder/path/fyne_dedicate.go
- fastbuilder/i18n/fyne_dedicate.go
Remove redundant files about fyne-gui
> Remove redundant files about fyne-gui

- fastbuilder/core/core.go
由于 `fastbuilder/core/core.go` 中的 `func EnterWorkerThread(env *environment.PBEnvironment, breaker chan struct{})` 中存在下列代码，因此这会导致其后方的 `case *packet.PyRpc` 代码块被永久屏蔽，从而导致 `Omega` 发不出命令。
现在，相关的代码块已经进行提前处理。
```go
if env.OmegaAdaptorHolder != nil {
env.OmegaAdaptorHolder.(*embed.EmbeddedAdaptor).FeedPacketAndByte(pk, data)
continue
}
```
详见
https://github.com/LNSSPsd/PhoenixBuilder/blob/cfb1d4e88ba7b33b00577486b0f72fc111f10c7f/fastbuilder/core/core.go#L387
https://github.com/LNSSPsd/PhoenixBuilder/blob/cfb1d4e88ba7b33b00577486b0f72fc111f10c7f/fastbuilder/core/core.go#L406
需要说明的是，此问题只有在使用 `Omega` 时才会发生。
> 修复无法使用 `Omega` 的问题

- fastbuilder/bdump/block_nbt/command_block.go
- fastbuilder/bdump/block_nbt/sign.go
- fastbuilder/environment/interfaces/game_interface.go
- fastbuilder/function/presets.go
- game_control/game_interface/anvil_generator.go
- game_control/game_interface/anvil_operation.go
- game_control/game_interface/commands.go
- game_control/game_interface/constants.go
- game_control/game_interface/setblock.go
- game_control/game_interface/structure_backup.go
- game_control/resources_control/command.go
- io/special_tasks/lexport.go
- solutions/fastbuilder/core.go
改进了命令请求的处理部分，当请求太久未被回应时，视为被屏蔽并返回错误信息。
本次更改主要是为了解决部分情况下 `setblock` 指令会被屏蔽的问题，现在导入部分特殊方块将不会再发生卡死。
目前设置的最长等待期限为 `1 second` 。
> Time out support for command request and fix related bugs

- .github/workflows/check.yml
> 给拉取请求添加构建检查

- fastbuilder/pv4/nemc_access_wrapper.go
> Fix error print
